### ISSUE TITLE
CurseForge Java UTF-8 Emoji Issue

### ISSUE THREAD

**Issue by BaerettStaffUp** [Hamster-Systems/HBM-Hamster-Reloaded-Official-Server-Pack#2]
On CurseForge, the name of the pack directory is "💣HBM Hamster Reloaded Official Server Pack💣". CurseForge somewhat uniquely comes packaged with its own Java to make things easier on users, HOWEVER, the Java it comes with is a bit out of date and **does not support UTF-8 encoding!**

This means if a user tries to start the pack on the CurseForge launcher (which is a lot of users seeing how popular that launcher is), it won't start and will give them a weird "Invalid Path" error. _This can be solved by removing the emojis from the pack's .ZIP name_, which is what both me and Blue_Bullet did, and now we're playing using CurseForge with no issues.

I also suspect this is what's wrong with discord user Djamy's game, since they said they were using the Curseforge launcher and the pack crashed immediately on launch.

**Comment by Coldalliance** [comment]
Fixed.
